spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mystudent
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


  #spring.mvc.date-format: yyyy-MM-dd

